name: Update PAC
on:
  push:
  schedule:
    - cron: '00 04 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: pac&acl
      
      - name: setup python
        uses: actions/setup-python@master

      - name: run script & commit files
        run: |
          pip3 install -r requirements.txt
          python3 unblockchn.py acl --pac
          python3 unblockchn.py acl --acl
          mv ./acl/china.acl ./acl/PAC.txt ./myacl/
          echo "This is your current acl files:"
          ls -al ./myacl/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./myacl
          publish_branch: production  # default: gh-pages
          commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

