name: Update PAC
on:
  push:
  schedule:
    - cron: '00 04 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: pac&acl
      
      - name: setup python
        uses: actions/setup-python@master

      # Remember: docker的每一步是隔离的，不能把run script单独写出来，会被清理掉。
      - name: run script & commit files
        run: |
          pip3 install -r requirements.txt
          python3 unblockchn.py acl
          cd ./acl/
          touch test.txt
          ls -al ./acl/
          pwd
          git status
          git config --local user.email "am1006@pm.me"
          git config --local user.name "am1006.github.actions"
          git add .
          git commit -m "update pac" || echo "nothing to update"
          git log --pretty=oneline

          #       - name: add and commit
          #         uses: stefanzweifel/git-auto-commit-action@master
          #         with:
          #           commit_massage: Update PAC

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'pac&acl'
          github_token: ${{ secrets.ACC_TOKEN }}


